# Generated by Django 3.2.8 on 2021-11-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20211104_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_email_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_full_name',
        ),
    ]
