# Generated by Django 3.2.8 on 2021-11-13 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersignups',
            options={'verbose_name_plural': "Newsletter Sign-up's"},
        ),
    ]
