# Generated by Django 3.2.8 on 2021-10-28 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211025_2131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogposts',
            options={'verbose_name_plural': 'Blog Posts'},
        ),
    ]
